name: senemarket
description: "SeneMarket provides a secure, intelligent and student-focused marketplace."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  image_picker: ^1.1.2
  firebase_storage: ^12.4.4
  cached_network_image: ^3.2.3
  dotted_border: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/senemarket-logo.png

  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
        - asset: assets/fonts/Cabin-Bold.ttf
          weight: 700